### PR TITLE
Added support for android@11.0.0

### PR DESCRIPTION
**Pull request by coderbuzz**
Added support for android@11.0.0
- Fix android:exported needs to be explicitly specified for Apps targeting Android 12 and higher are required to specify

### CODE REVIEW

**Review by alindzon — APPROVED** [review]

**Comment by RsknCankov** [comment]
Guys why this is still not merged? So simple change, enabling us to deploy on android 12+ 

@ToniKorin

**Review by RsknCankov — APPROVED** [review]

**Comment by coderbuzz** [comment]
The last @ToniKorin activity was October 16 2022 

Maybe something is causing him not to login to github for the last few months

**Comment by gallyamow** [comment]
didn't you forget to publish plugin to npm? I'm installed 2.3.0 it and receive no changes. I reinstalled plugin from github and it fix es the problem.

**Comment by ToniKorin** [comment]
Sorry, I have no time to maintain this anymore. Please fork it and publish it to npm with another name.

**Comment by gallyamow** [comment]
Hi, no problem. 

> Sorry, I have no time to maintain this anymore. Please fork it and publish it to npm with another name.

**Pull request merged**
